version: 'pre-release'

# Define a matrix of configurations for different OS environments
matrix:
  fast_finish: true
  include:
    - os: Windows
      image: Visual Studio 2022
      configuration: Release
      platform: x64
    - os: macOS
      image: macos-12
      configuration: Release
    - os: Linux
      image: Ubuntu
      configuration: Release

# Install dependencies
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Build process for Electron
build_script:
  - echo "Building for Electron..."
  - npm run make

# Define artifacts (built files) to be stored
artifacts:
  - path: './dist/*.exe'
    name: Windows
  - path: './dist/*.dmg'
    name: macOS
  - path: './dist/*.AppImage'
    name: Linux

# Environment variables
environment:
  nodejs_version: '16.13.1'
  electron_version: '16.0.6'