version: 'pre-release'

# Define a matrix of configurations for different OS environments
matrix:
  fast_finish: true
  # Define the jobs here for different platforms
  jobs:
    - environment:
        nodejs_version: '16.13.1'
        electron_version: '16.0.6'
      install:
        - ps: Install-Product node $env:nodejs_version
        - npm install
      build_script:
        - echo "Building for Windows..."
        - npm run make
      artifacts:
        - path: './dist/*.exe'
          name: Windows

    - os: macOS
      image: macos-12
      environment:
        nodejs_version: '16.13.1'
        electron_version: '16.0.6'
      install:
        - ps: Install-Product node $env:nodejs_version
        - npm install
      build_script:
        - echo "Building for macOS..."
        - npm run make
      artifacts:
        - path: './dist/*.dmg'
          name: macOS

    - os: Ubuntu
      environment:
        nodejs_version: '16.13.1'
        electron_version: '16.0.6'
      install:
        - ps: Install-Product node $env:nodejs_version
        - npm install
      build_script:
        - echo "Building for Linux..."
        - npm run make
      artifacts:
        - path: './dist/*.AppImage'
          name: Linux

# Install dependencies
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Build process for Electron
build_script:
  - echo "Building for Electron..."
  - npm run make

# Define artifacts (built files) to be stored
artifacts:
  - path: './dist/*.exe'
    name: Windows
  - path: './dist/*.dmg'
    name: macOS
  - path: './dist/*.AppImage'
    name: Linux

# Environment variables
environment:
  nodejs_version: '16.13.1'
  electron_version: '16.0.6'